apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "2"
  labels:
    app: nginx-foosbal
  name: nginx-foosbal
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-foosbal
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-foosbal
  name: nginx-foosbal
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-foosbal
  template:
    metadata:
      labels:
        app: nginx-foosbal
    spec:
      containers:
      - image: 0x6170/nginx:foosbal-score-keeper
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 1m
            memory: 64Mi
        volumeMounts:
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-run
      volumes:
      - emptyDir: {}
        name: nginx-cache
      - emptyDir: {}
        name: nginx-run
